project_id = "pytefsexxwtlropzkmxi"

[functions.generate-ai-suggestion]
verify_jwt = true

[functions.sync-google-calendar]
verify_jwt = true

[functions.refresh-google-token]
verify_jwt = true

[functions.add-to-google-calendar]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.delete-google-event]
verify_jwt = true

[functions.update-google-event]
verify_jwt = true

[functions.recalculate-suggestions]
verify_jwt = true

[functions.check-period-notifications]
verify_jwt = false